name: test_2019
on:
  push:
    paths:
      - 'years/2019/**/*'
jobs:
  setup_2019:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
            days=$(ls years/2019 | grep ^d | sed 's/^.\{1,\}$/{"dir": "&"}/' |tr '\n' ',')
            output="matrix={\"include\":[${days%?}]}"
            echo "$output" >> $GITHUB_OUTPUT
  test_2019:
    name: Test 2019
    needs: [ setup_2019 ]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup_2019.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Run Tests
        run: cargo +nightly test
        working-directory: "years/2019/${{ matrix.dir }}"
