name: test_2024

on:
  push:
    branches:
      - main
    paths:
      - 'years/2024/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install dependencies
        working-directory: years/2024
        run: go mod tidy

      - name: Run tests
        working-directory: years/2024
        run: go test ./... -v

