name: test_2023
on:
  push:
    paths:
      - 'years/2023/**/*'
jobs:
  setup_2022:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
            days=$(ls years/2023 | grep ^d | sed 's/^.\{1,\}$/{"dir": "&"}/' |tr '\n' ',')
            output="matrix={\"include\":[${days%?}]}"
            echo "$output"
            echo "$output" >> $GITHUB_OUTPUT
  test_2022:
    name: Test 2023
    needs: [ setup_2023 ]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup_2023.outputs.matrix) }}
    steps:
      - uses: actions/checkout@4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Test part A
        run: cargo +nightly test
        working-directory: years/2023/${{ matrix.dir }}/a
      - name: Test part B
        run: cargo +nightly test
        working-directory: years/2023/${{ matrix.dir }}/b
